parameters:
- name: ArtifactName
  type: string
  default: packages
- name: ProjectName
  type: string
  default: ''

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6 Core sdk'
        inputs:
          packageType: 'sdk'
          version: '6.0.x'
          includePreviewVersions: true
          
      - task: DotNetCoreCLI@2
        displayName: 'Dotnet Restore ${{parameters.ProjectName}}'
        inputs:
          command: 'restore'
          projects: 'src/${{ parameters.ProjectName }}/**/${{ parameters.ProjectName }}.csproj'
          arguments: '-c $(BuildConfiguration) --force'

      - task: DotNetCoreCLI@2
        displayName: 'Dotnet Build ${{parameters.ProjectName}}'
        inputs:
          command: 'build'
          projects: 'src/${{ parameters.ProjectName }}/**/${{ parameters.ProjectName }}.csproj'
          arguments: -c $(BuildConfiguration)

      - task: DotNetCoreCLI@2
        displayName: 'Execute Tests'
        inputs:
          command: 'test'
          projects: 'src/${{ parameters.ProjectName }}/tests/*.csproj'
          arguments: '/p:CollectCoverage=true'

      - task: DotNetCoreCLI@2
        displayName: 'Dotnet Pack ${{ parameters.ProjectName }}'
        inputs:
          command: 'pack'
          packagesToPack: 'src/${{ parameters.ProjectName }}/**/${{ parameters.ProjectName }}.csproj'
          nobuild: true
          versioningScheme: 'off'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish ${{parameters.ProjectName}} Artifacts'
        condition: succeeded()
        inputs:
          artifactName: '${{parameters.ArtifactName}}'
          path: $(Build.ArtifactStagingDirectory)
