<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Creators\MessageBrokers\AzureServiceBus\**" />
    <EmbeddedResource Remove="Creators\MessageBrokers\AzureServiceBus\**" />
    <None Remove="Creators\MessageBrokers\AzureServiceBus\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Creators\AzureServiceBus\" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.27" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Chatter.MessageBrokers.Reliability.EntityFramework\src\Chatter.MessageBrokers.Reliability.EntityFramework\Chatter.MessageBrokers.Reliability.EntityFramework.csproj" />
  </ItemGroup>

</Project>
