using System;
using System.Collections.Generic;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Cosmos;

namespace Chatter.MessageBrokers.Reliability.Cosmos.Tests.Integration
{
    // Edge-of-the-test read helpers over the emulator. The suite drives writes through Chatter's public contracts; these
    // helpers only OBSERVE the committed result at the edge (point-reads + partition-scoped count queries). They never
    // act as the system under test.
    //
    // The co-resident outbox doc id is outbox:{encoded(MessageId)} where the MessageId of the handler's follow-up Send
    // is generated by Chatter's IMessageIdGenerator (the SendOptions.MessageId scalar does NOT survive the
    // handler-context Send merge in the core library), so the test cannot predict it. Therefore outbox/inbox doc
    // presence is asserted by COUNTING Chatter docs of a given _chatterType in the partition rather than by a predicted
    // id.
    internal static class CosmosEdge
    {
        // Point-read presence at a known id. Bounded retry tolerates the brief read-your-write window the emulator may
        // exhibit immediately after a batch commit.
        public static async Task<bool> WaitForPresenceAsync(Container container, string id, string partition, bool expectPresent, TimeSpan timeout)
        {
            DateTime deadline = DateTime.UtcNow + timeout;
            bool present;
            do
            {
                using ResponseMessage read = await container.ReadItemStreamAsync(id, new PartitionKey(partition));
                present = read.StatusCode == HttpStatusCode.OK;
                if (present == expectPresent)
                {
                    return present;
                }

                await Task.Delay(TimeSpan.FromMilliseconds(200));
            }
            while (DateTime.UtcNow < deadline);

            return present;
        }

        // Counts the Chatter documents carrying the given _chatterType discriminator within a partition. Used to assert
        // outbox/inbox doc presence/absence without a predicted id.
        public static async Task<int> CountByChatterTypeAsync(Container container, string chatterType, string partition)
        {
            var query = new QueryDefinition($"SELECT VALUE COUNT(1) FROM c WHERE c[\"{CosmosOutboxDocument.DiscriminatorField}\"] = @type")
                .WithParameter("@type", chatterType);

            using FeedIterator<int> iterator = container.GetItemQueryIterator<int>(
                query,
                requestOptions: new QueryRequestOptions { PartitionKey = new PartitionKey(partition) });

            int total = 0;
            while (iterator.HasMoreResults)
            {
                FeedResponse<int> page = await iterator.ReadNextAsync();
                foreach (int count in page)
                {
                    total += count;
                }
            }

            return total;
        }

        // Reads the MessageBody value(s) of the outbox doc(s) (_chatterType == "outbox") in a partition. The outbox doc
        // id is NOT predictable (SendOptions.MessageId does not survive the handler-context Send merge — see the type
        // remarks above), so the MessageBody is the command-distinguishing reconstruction field the multi-container fact
        // keys identity on: each command's follow-up Send serializes its DISTINCT sentinel Payload into this field. A
        // VALUE-string projection (not a JsonElement) is read so the strings stay valid past the feed page lifetime.
        public static async Task<IReadOnlyList<string>> ReadOutboxMessageBodiesAsync(Container container, string partition)
        {
            var query = new QueryDefinition(
                    $"SELECT VALUE c.{CosmosOutboxDocument.MessageBodyField} FROM c WHERE c[\"{CosmosOutboxDocument.DiscriminatorField}\"] = @type")
                .WithParameter("@type", CosmosItemId.OutboxKind);

            var bodies = new List<string>();
            using FeedIterator<string> iterator = container.GetItemQueryIterator<string>(
                query,
                requestOptions: new QueryRequestOptions { PartitionKey = new PartitionKey(partition) });

            while (iterator.HasMoreResults)
            {
                FeedResponse<string> page = await iterator.ReadNextAsync();
                foreach (string body in page)
                {
                    bodies.Add(body);
                }
            }

            return bodies;
        }

        // Bounded poll until the partition holds at least minCount outbox-doc MessageBody value(s), returning the last
        // observed snapshot (which may hold fewer than minCount if the timeout elapses) so a never-reached threshold
        // fails fast rather than hanging. Used to read per-container outbox identity by its command-distinguishing body.
        public static async Task<IReadOnlyList<string>> WaitForOutboxMessageBodiesAsync(Container container, string partition, int minCount, TimeSpan timeout)
        {
            DateTime deadline = DateTime.UtcNow + timeout;
            IReadOnlyList<string> bodies;
            do
            {
                bodies = await ReadOutboxMessageBodiesAsync(container, partition);
                if (bodies.Count >= minCount)
                {
                    return bodies;
                }

                await Task.Delay(TimeSpan.FromMilliseconds(200));
            }
            while (DateTime.UtcNow < deadline);

            return bodies;
        }

        // The projected wire shape of a single Chatter outbox document, read at the test edge for shape assertions.
        public readonly struct OutboxWireShape
        {
            public OutboxWireShape(string id, string chatterType, string status, string destination, string messageBody, string messageContentType, bool hasMessageContext)
            {
                Id = id;
                ChatterType = chatterType;
                Status = status;
                Destination = destination;
                MessageBody = messageBody;
                MessageContentType = messageContentType;
                HasMessageContext = hasMessageContext;
            }

            public string Id { get; }
            public string ChatterType { get; }
            public string Status { get; }
            public string Destination { get; }
            public string MessageBody { get; }
            public string MessageContentType { get; }
            public bool HasMessageContext { get; }
        }

        // Reads the single outbox doc (_chatterType == "outbox") in a partition and projects its wire shape (id,
        // discriminator, status, destination, body, content type, and whether a non-empty MessageContext is present). The
        // doc id is NOT predictable (SendOptions.MessageId does not survive the handler-context Send merge — see the type
        // remarks above), so the doc is located by its _chatterType=outbox discriminator via a VALUE-string id projection
        // (safe across the feed page lifetime, unlike a JsonElement projection), then point-read as a test-owned stream
        // parsed with System.Text.Json — NOT GetItemQueryIterator<JsonElement>, whose elements are disposed with the feed
        // page. Returns null when no outbox doc is present.
        public static async Task<OutboxWireShape?> ReadOutboxWireShapeAsync(Container container, string partition)
        {
            var query = new QueryDefinition(
                    $"SELECT VALUE c.{CosmosOutboxDocument.IdField} FROM c WHERE c[\"{CosmosOutboxDocument.DiscriminatorField}\"] = @type")
                .WithParameter("@type", CosmosItemId.OutboxKind);

            string outboxId = null;
            using (FeedIterator<string> iterator = container.GetItemQueryIterator<string>(
                query,
                requestOptions: new QueryRequestOptions { PartitionKey = new PartitionKey(partition) }))
            {
                while (iterator.HasMoreResults && outboxId is null)
                {
                    FeedResponse<string> page = await iterator.ReadNextAsync();
                    foreach (string id in page)
                    {
                        outboxId = id;
                        break;
                    }
                }
            }

            if (outboxId is null)
            {
                return null;
            }

            using ResponseMessage read = await container.ReadItemStreamAsync(outboxId, new PartitionKey(partition));
            if (read.StatusCode != HttpStatusCode.OK)
            {
                return null;
            }

            using JsonDocument document = await JsonDocument.ParseAsync(read.Content);
            JsonElement root = document.RootElement;
            return new OutboxWireShape(
                id: ReadString(root, CosmosOutboxDocument.IdField),
                chatterType: ReadString(root, CosmosOutboxDocument.DiscriminatorField),
                status: ReadString(root, CosmosOutboxDocument.StatusField),
                destination: ReadString(root, CosmosOutboxDocument.DestinationField),
                messageBody: ReadString(root, CosmosOutboxDocument.MessageBodyField),
                messageContentType: ReadString(root, CosmosOutboxDocument.MessageContentTypeField),
                hasMessageContext: root.TryGetProperty(CosmosOutboxDocument.MessageContextField, out JsonElement context)
                    && context.ValueKind == JsonValueKind.String
                    && !string.IsNullOrEmpty(context.GetString()));
        }

        private static string ReadString(JsonElement root, string field)
            => root.TryGetProperty(field, out JsonElement element) && element.ValueKind == JsonValueKind.String
                ? element.GetString()
                : null;

        // Bounded poll until the partition holds at least minCount Chatter docs of the given type, returning the last
        // observed count (which may be below minCount if the timeout elapses) so a never-reached threshold fails fast.
        public static async Task<int> WaitForCountByChatterTypeAsync(Container container, string chatterType, string partition, int minCount, TimeSpan timeout)
        {
            DateTime deadline = DateTime.UtcNow + timeout;
            int observed;
            do
            {
                observed = await CountByChatterTypeAsync(container, chatterType, partition);
                if (observed >= minCount)
                {
                    return observed;
                }

                await Task.Delay(TimeSpan.FromMilliseconds(200));
            }
            while (DateTime.UtcNow < deadline);

            return observed;
        }
    }
}
