trigger:
  branches:
    include:
      - master
      - feature/*
      - hotfix/*
      - bugfix/*
      - release/*

  paths:
    include:
      - src/Chatter.MessageBrokers.Reliability.EntityFramework/*

pr:
  branches:
    include:
      - master
      - hotfix/*
      - release/*

extends:
  template: ../../../eng/pipelines/stages/chatter-ci-cd.yml
  parameters:
    ProjectName: Chatter.MessageBrokers.Reliability.EntityFramework
    ArtifactName: packages
