trigger:
  branches:
    inclues:
      - master

  paths:
    include:
      - src/Chatter.MessageBrokers/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'
  ProjectName: 'Chatter.MessageBrokers'
  PathToCsProj: 'src/$(ProjectName)/**/$(ProjectName).csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '$(PathToCsProj)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(PathToCsProj)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(PathToCsProj)'
    nobuild: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/$(ProjectName)*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'
    allowPackageConflicts: true
    versioningScheme: 'off'