<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Aggregates\" />
    <Folder Include="Entities\" />
    <Folder Include="Events\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Repositories\" />
    <Folder Include="Services\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

</Project>
